### ISSUE TITLE
InstallWindowsScheduledTask@2 fails - Task is installed, but disabled

### ISSUE THREAD

**Issue by benzhi** [deadlydog/AzureDevOps.WindowsScheduledTasks#24] opened 2023-02-09 10:37 UTC
When running the task, a scheduled task is registered, but disabled, ultimately failing my deployment job. I can manually start the scheduled task in the task scheduler, but failure of the job prevents deployment to following stages of my deployment pipeline.

I see the following error in the terminal output:
```powershell
##[error]Microsoft.Management.Infrastructure.CimException: The task is disabled.

   at Microsoft.Management.Infrastructure.Internal.Operations.CimAsyncObserverProxyBase`1.ProcessNativeCallback(OperationCallbackProcessingContext callbackProcessingContext, T currentItem, Boolean moreResults, MiResult operationResult, String errorMessage, InstanceHandle errorDetailsHandle)
##[error]PowerShell script completed with 1 errors.
```

I also see the following warning at the top of all WindowsScheduledTasks tasks I use (stop, uninstall, etc.):
```powershell
##[warning]Task 'InstallWindowsScheduledTask' (2.3.12) is using deprecated task execution handler. The task should use the supported task-lib: https://aka.ms/tasklib
```

Don't know whether that may have to do with the issue. Apart from the stacktrace above, I don't see any other logging that helps me troubleshoot the issue.

**Comment by deadlydog** [comment] 2023-02-14 16:55
Hey @benzhi , the `deprecated task execution handler` warning is unrelated and should not affect anything.

Are you using `Inline` for the Scheduled Task Definition Source? Do you have the task set to be `Enabled` after it's installed?

![image](https://user-images.githubusercontent.com/1187140/218803413-128e5e56-c110-483d-af0c-82aeac00f207.png)

If you are not using the `Inline` method and instead using an XML definition, be sure that the task is enabled in the XML.

![image](https://user-images.githubusercontent.com/1187140/218804531-f927e2a1-0325-4b4e-b196-bb873ed6f018.png)

**Comment by benzhi** [comment] 2023-02-15 10:29
Hey @deadlydog ,

thanks for reaching out!
I am using the Xml-file option, with the task Enabled node value set to 'true'.
However, that was not the problem; a colleague told me he had problems with scheduling executables but not with powershell scripts on newer Server OS-es, so I created a mini ps1 file with the simple task '& $exe $args', replaced the executable link in the XML with the ps1 link and now it works.
The funny thing is, when I used the executable link in the XML file, the installation task failed, but the scheduled task was installed, but disabled. I could enable the task and it would work like a charm. The only problem is, that I use multiple stages and I would never be able to move to the next stage of my pipeline because of the failed task. 
There would be two solutions to this: get rid of the error when using a direct path to the executable in my task (ideal), or if the task would have an option to ignore errors, like some other tasks (I think powershell task?) have.

**Comment by deadlydog** [comment] 2023-02-15 16:38
Thanks for the information and for sharing your workaround. I use the extension to install Scheduled Tasks for executables on a few different servers and haven't run into this issue. I think the latest OS I'm installing to is Windows Server 2019 or 2016 though.

> or if the task would have an option to ignore errors

All tasks in Azure DevOps allow you to continue even if they fail. When using the classic view it's in the `Control Options` section.

![image](https://user-images.githubusercontent.com/1187140/219091711-946bc752-a071-41fe-b735-b576ff4eb936.png)

I typically don't recommend this though since it would ignore other legitimate failures as well and continue when you might actually want it to stop your pipeline.

Since there's a workaround, unless more people report the issue or I am able to reproduce it myself, I'm going to leave it for now and close this issue. Thanks for reporting it and sharing the workaround though!

**Closed as completed by deadlydog** 2023-02-15 16:38 UTC
